### ISSUE TITLE
Italian corpus doesn't load correctly

### ISSUE THREAD

**Issue by lehkost** [dracor-org/dracor-shiny#6]
I don't remember if the Italian corpus ever worked in our Shiny App. The problem could by the anonymous plays. They figure as "NA" in the authors menu. I can't think of any other general differences to the rest of the corpora, which all seem to work fine.

**Comment by lehkost** [comment]
rdracor has the same problem, obviously connected to anonymous authors (and, thus, missing Wikidata IDs?), see screenshot:

![itadracor-problem](https://user-images.githubusercontent.com/6539515/92253402-bb864000-eecf-11ea-9d93-73dadd86c43b.png)

**Comment by lehkost** [comment]
It seems this was fixed in the recent update, at least I can now choose the Italian corpus and scroll through authors and plays. If you can confirm, @Pozdniakov @cmil, you can close this issue.

**Comment by cmil** [comment]
Confirmed.
